#ifndef R1_SUPERSTRUCTURE_GLOBAL_MOTOR_CONF_H
#define R1_SUPERSTRUCTURE_GLOBAL_MOTOR_CONF_H

typedef enum {
    DJI_YL_G = 0,
    DJI_YR_G,
    DJI_XL_G,
    DJI_XR_G,
    DJI_JOINT1_3508_G,
    DJI_JOINT2_2006_G,
    DM_FRONT_LEFT_G,
    DM_FRONT_RIGHT_G,
    XIAOMI_MOTOR1_G,
    XIAOMI_MOTOR2_G,
    UNITREE_GO_M8010_6_MOTOR1_G,
    UNITREE_GO_M8010_6_MOTOR2_G,
    BLAZER_FOC_MOTOR1_G,
    BLAZER_FOC_MOTOR2_G,
    BLAZER_FOC_MOTOR3_G,
    BLAZER_FOC_MOTOR4_G,
} Global_Motor_Index_e;

#endif /* R1_SUPERSTRUCTURE_GLOBAL_MOTOR_CONF_H */
